[build]
  base = "WaifuCore/Frontend"
  command = """
    npm install
    npm run build
  """
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_APP_BASE_URL = "/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false
