[build]
  base = "WaifuCore/Frontend"
  command = "CI= npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--no-audit --no-optional"
  NETLIFY_USE_YARN = "false"

[build.processing]
  skip_processing = false
