gemini_api_key: "YOUR_GEMINI_API_KEY"
groq_api_key: 

# --- Service Configurations ---
llm:
  # Models for each provider. The code will pick the right one.
  models:
    gemini: "gemini-1.5-flash"  # Free tier model with good performance
    groq-llama3-8b-8192: "llama3-8b-8192"
    groq-llama3-70b-8192: "llama3-70b-8192"
    groq-mixtral-8x7b-32768: "mixtral-8x7b-32768"
    groq-gemma-7b-it: "gemma-7b-it"
    groq-llama-3.1-8b-instant: "llama-3.1-8b-instant"
    groq-llama-3.1-70b-versatile: "llama-3.1-70b-versatile"
    ollama: "llama3"
  temperature: 0.8
  max_tokens: 200

asr:
  model_size: "base" # "base", "small", "medium", "large-v3"
  device: "cpu"
  compute_type: "int8"

memory:
  db_path: "/tmp/local_db"
  retrieval_results: 3 # How many memories to fetch for context

tts:
  provider: "elevenlabs"  # Options: "kokoro", "elevenlabs", "coqui"
  
  # Coqui TTS Server (for high-quality voice cloning)
  coqui:
    api_url: "http://localhost:5002/api/tts"
    language: "en"
    reference_voice: "assets/character_voices/ananya_happy.wav"
    device: "cpu"

  # Kokoro TTS (for fast, direct library usage)
  kokoro:
    model_dir: "models/kokoro"
    voice: "af_heart" # A built-in high-quality female voice
    device: "cpu"

  # ElevenLabs TTS (for premium cloud-based voice synthesis)
  elevenlabs:
    # API key can be set via environment variable ELEVENLABS_API_KEY or here
    api_key: 
    voice_id: "21m00Tcm4TlvDq8ikWAM"  # Rachel - young, clear voice
    model_id: "eleven_turbo_v2"  # Latest model for best quality
    voice_settings:
      stability: 0.3        # Lower stability for more expressive/dynamic speech
      similarity_boost: 0.8 # Higher similarity to maintain voice character
      style: 0.7           # Higher style for more emotional/anime-like delivery
      use_speaker_boost: true # Enhances similarity to original speaker
