gemini_api_key: "YOUR_GEMINI_API_KEY"
groq_api_key: 

# --- Service Configurations ---
llm:
  # Models for each provider. The code will pick the right one.
  models:
    gemini: "gemini-1.5-flash"  # Free tier model with good performance
    groq: "llama3-8b-8192"
    ollama: "llama3"
  temperature: 0.8
  max_tokens: 200

asr:
  model_size: "base" # "base", "small", "medium", "large-v3"
  device: "cuda"      # "cuda" or "cpu"
  compute_type: "float16" # "float16" for GPU, "int8" for smaller models

memory:
  db_path: "waifu_core/local_db"
  retrieval_results: 3 # How many memories to fetch for context

tts:
  provider: "kokoro"  # Options: "kokoro", "elevenlabs", "coqui"
  
  # Coqui TTS Server (for high-quality voice cloning)
  coqui:
    api_url: "http://localhost:5002/api/tts"
    language: "en"
    # The single, high-quality reference file for voice cloning
    reference_voice: "assets/character_voices/ananya_happy.wav"

  # Kokoro TTS (for fast, direct library usage)
  kokoro:
    model_dir: "models/kokoro"
    voice: "af_heart" # A built-in high-quality female voice
    device: "cuda"

  # ElevenLabs TTS (for premium cloud-based voice synthesis)
  elevenlabs:
    # API key can be set via environment variable ELEVENLABS_API_KEY or here
    api_key: 
    voice_id: "Rachel"  # Voice ID or name (e.g., "Rachel", "Domi", "Bella", etc.)
    model_id: "eleven_monolingual_v1"  # or "eleven_multilingual_v1", "eleven_turbo_v2"
    voice_settings:
      stability: 0.75        # 0.0 to 1.0 - Lower is more variable/expressive
      similarity_boost: 0.75 # 0.0 to 1.0 - Higher is more similar to original voice
      style: 0.0            # 0.0 to 1.0 - Adds more style/emotion
      use_speaker_boost: true # Enhances similarity to original speaker
